# Einstellungen 

# Anzahl der Linien, also der Verfügbaren RS485 Linien
LINES = 2


# Die Line Sektionen werden stumpf durchnummeriert, z.B. Line1, Line2, ...
# CONTYPE: RTU oder TCP
# URL: COM Port oder IP Adresse
# ORT:  Kurze Raumbezeichung, z.B. R10, R01, D01, R14.1, 
#       Hinweis: Die ORT-Bezeichnung wird auch für die Dateinamen verwendet.  
#       Darf keine Zeichen enthalten, die für Dateinamen problematisch sind 
#       (z.B. / \ : * ? " < > |)
#       R14/2 geht nicht!!
# ID: Liste der Geräte IDs auf der Linie, durch Komma getrennt

[Line1]
CONTYPE = RTU
URL = COM3
ORT = R08
ID = 33, 34, 35, 36

[Line2]
CONTYPE = RTU
URL = COM4
ORT = R09
ID = 37, 38, 39, 40

[Line3]
URL = COM3
CONTYPE = RTU
ORT = 2
ID = 5,6,7,8

[Line4]
CONTYPE = RTU
URL = COM4
ORT = 2
ID = 9,10,11,12
