# Einstellungen 

# Anzahl der Linien, also der Verfügbaren RS485 Linien
LINES = 4


# Die Line Sektionen werden stumpf durchnummeriert, z.B. Line1, Line2, ...
# CONTYPE: RTU oder TCP
# URL: COM Port oder IP Adresse
# ORT: Raumnummer 
# ID: Liste der Geräte IDs auf der Linie, durch Komma getrennt

[Line1]
CONTYPE = RTU
URL = COM1
ORT = 8
ID = 1,2,3,4

[Line2]
CONTYPE = RTU
URL = COM2
ORT = 2
ID = 5,6,7,8

[Line3]
URL = COM3
CONTYPE = RTU
ORT = 2
ID = 5,6,7,8

[Line4]
CONTYPE = RTU
URL = COM4
ORT = 2
ID = 9,10,11,12
